"""Tests for the flow-props CLI (init / run / examples)."""

from pathlib import Path

from typer.testing import CliRunner

from flow_props.cli.app import app

runner = CliRunner()


def test_version_short_flag():
    result = runner.invoke(app, ["-V"])
    assert result.exit_code == 0
    assert "flow-props" in result.output


def test_no_args_shows_help():
    result = runner.invoke(app, [])
    # no_args_is_help exits with code 0 and prints usage
    assert "Usage" in result.output
    assert "init" in result.output
    assert "run" in result.output
    assert "examples" in result.output


def test_init_writes_full_config(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    result = runner.invoke(app, ["init"])
    assert result.exit_code == 0

    config_text = Path("flow_props.toml").read_text()
    assert "[stations]" in config_text
    assert "[bl]" in config_text
    assert "[gas]" in config_text
    assert "generated by: flow-props init" in config_text


def test_init_bl_writes_bl_config(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    result = runner.invoke(app, ["init", "--bl"])
    assert result.exit_code == 0

    assert Path("bl.toml").is_file()
    config_text = Path("bl.toml").read_text()
    assert "generated by: flow-props init --bl" in config_text
    assert "[bl]" in config_text


def test_init_requires_force_to_overwrite(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    assert runner.invoke(app, ["init"]).exit_code == 0

    result = runner.invoke(app, ["init"])
    assert result.exit_code != 0
    assert "already exists" in result.output

    result = runner.invoke(app, ["init", "--force"])
    assert result.exit_code == 0


def test_run_missing_default_config_reports_not_found(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    result = runner.invoke(app, ["run"])
    assert result.exit_code != 0
    assert "not found" in result.output


def test_run_bl_missing_explicit_config_reports_not_found(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    result = runner.invoke(app, ["run", "--bl", "nonexistent.toml"])
    assert result.exit_code != 0
    assert "not found" in result.output


def test_examples_lists_available(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    result = runner.invoke(app, ["examples"])
    assert result.exit_code == 0
    assert "sharp_flat_plate_m5" in result.output
    assert "ogive_m5pt3" in result.output
    assert "cone_7deg_m14" in result.output


def test_examples_copies_named_config(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    result = runner.invoke(app, ["examples", "sharp_flat_plate_m5"])
    assert result.exit_code == 0

    config_text = Path("sharp_flat_plate_m5.toml").read_text()
    assert "[stations]" in config_text
    assert "[bl]" in config_text


def test_examples_refuses_to_overwrite(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    assert runner.invoke(app, ["examples", "ogive_m5pt3"]).exit_code == 0

    result = runner.invoke(app, ["examples", "ogive_m5pt3"])
    assert result.exit_code != 0
    assert "already exists" in result.output


def test_examples_unknown_name_errors(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    result = runner.invoke(app, ["examples", "bogus_case"])
    assert result.exit_code != 0
    assert "unknown example" in result.output
