"""CLI subcommand: flow-props init"""

from __future__ import annotations

from pathlib import Path

import typer

# -- BL-only template (written by: flow-props init --bl) --
BL_TEMPLATE = """\
# flow-props BL configuration
# generated by: flow-props init --bl
# run with:     flow-props run --bl

# -- input --
fname = "flow.s8"        # path to CFD solution file (.s8, .hdf5, ...)
gname = "grid.s8"        # grid file for split-format CFD++ (leave blank for HDF5)

# -- station selection: pick EXACTLY ONE mode --

[stations]
# mode 1 (default): x-range along the wall surface (recommended)
x_s = 0.05              # start x [m]
x_e = 0.50              # end x [m]
dx  = 0.05              # step [m]

# mode 2: i-index range
# i_s = 10
# i_e = 500
# di  = 10

# mode 3: explicit list of i-stations
# list = [10, 50, 100, 200]

# -- boundary layer extraction --

[bl]
criterion = "velocity_ratio"    # velocity_ratio | htot_derivative
threshold = 0.99                # threshold for velocity_ratio (fraction of edge velocity)
output    = "bl_properties.dat" # output Tecplot ASCII file

# -- gas properties --

[gas]
gamma        = 1.4      # specific heat ratio
gas_constant = 287.05   # gas constant [J/(kg K)]
"""

# -- full template (written by: flow-props init) --
FULL_TEMPLATE = """\
# flow-props configuration
# generated by: flow-props init
# run with:     flow-props run
#
# Tip: for BL-only runs use: flow-props init --bl  ->  bl.toml

# -- input --
fname = "flow.s8"        # path to CFD solution file (.s8, .hdf5, ...)
gname = "grid.s8"        # grid file for split-format CFD++ (leave blank for HDF5)

# -- station selection: pick EXACTLY ONE mode --

[stations]
x_s = 0.05
x_e = 0.50
dx  = 0.05

# -- boundary layer extraction --

[bl]
criterion = "velocity_ratio"    # velocity_ratio | htot_derivative
threshold = 0.99
output    = "bl_properties.dat"

# -- gas properties --

[gas]
gamma        = 1.4
gas_constant = 287.05
"""


def cmd_init(
    bl: bool = typer.Option(False, "--bl", help="Write BL-only config (bl.toml)."),
    force: bool = typer.Option(False, "--force", help="Overwrite existing config."),
) -> None:
    """Write a default config file in the current directory.

    Without flags: writes flow_props.toml (full template).
    With --bl:     writes bl.toml (BL extraction only).
    """
    # select template and filename based on mode
    if bl:
        dest = Path("bl.toml")
        template = BL_TEMPLATE
        run_hint = "flow-props run --bl"
    else:
        dest = Path("flow_props.toml")
        template = FULL_TEMPLATE
        run_hint = "flow-props run"

    # check target path
    if dest.exists() and not force:
        typer.echo(f"Error: {dest} already exists. Use --force to overwrite.", err=True)
        raise typer.Exit(code=1)

    # write template
    dest.write_text(template, encoding="utf-8")
    typer.echo(f"Written {dest}")
    typer.echo(f"Edit the file then run:  {run_hint}")
